//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertsureWebAndLoadTest
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Microsoft.VisualStudio.TestTools.WebTesting.Rules;


    public class LoadHomePageCoded : WebTest
    {

        public LoadHomePageCoded()
        {
            this.PreAuthenticate = true;
            this.Proxy = "default";
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            // Initialize validation rules that apply to all requests in the WebTest
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidateResponseUrl validationRule1 = new ValidateResponseUrl();
                this.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule1.Validate);
            }
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidationRuleResponseTimeGoal validationRule2 = new ValidationRuleResponseTimeGoal();
                validationRule2.Tolerance = 0D;
                this.ValidateResponseOnPageComplete += new EventHandler<ValidationEventArgs>(validationRule2.Validate);
            }

            WebTestRequest request1 = new WebTestRequest("http://uat.niceiconline.com/");
            WebTestRequest request1Dependent1 = new WebTestRequest("http://uat.niceiconline.com/static/css/fonts/OpenSans-Light.woff");
            request1Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "http://uat.niceiconline.com/"));
            request1.DependentRequests.Add(request1Dependent1);
            WebTestRequest request1Dependent2 = new WebTestRequest("http://uat.niceiconline.com/static/css/fonts/OpenSans.woff");
            request1Dependent2.Headers.Add(new WebTestRequestHeader("Referer", "http://uat.niceiconline.com/"));
            request1.DependentRequests.Add(request1Dependent2);
            WebTestRequest request1Dependent3 = new WebTestRequest("http://uat.niceiconline.com/static/css/fonts/OpenSans-SemiBold.woff");
            request1Dependent3.Headers.Add(new WebTestRequestHeader("Referer", "http://uat.niceiconline.com/"));
            request1.DependentRequests.Add(request1Dependent3);
            WebTestRequest request1Dependent4 = new WebTestRequest("http://uat.niceiconline.com/static/css/fonts/OpenSans-Bold.woff");
            request1Dependent4.Headers.Add(new WebTestRequestHeader("Referer", "http://uat.niceiconline.com/"));
            request1.DependentRequests.Add(request1Dependent4);
            WebTestRequest request1Dependent5 = new WebTestRequest("http://uat.niceiconline.com/static/css/fonts/OpenSans-ExtraBold.woff");
            request1Dependent5.Headers.Add(new WebTestRequestHeader("Referer", "http://uat.niceiconline.com/"));
            request1.DependentRequests.Add(request1Dependent5);
            yield return request1;
            request1 = null;

            // load home page
            this.AddCommentToResult("load home page");
        }
    }
}
