//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertsureWebAndLoadTest
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Microsoft.VisualStudio.TestTools.WebTesting.Rules;


    public class NotifyLocalAuthorityCoded : WebTest
    {

        private WebTestDependentFilteryyy testPlugin = new WebTestDependentFilteryyy();

        public NotifyLocalAuthorityCoded()
        {
            this.PreAuthenticate = true;
            this.Proxy = "default";

            //this.PreRequest += new EventHandler<PreRequestEventArgs>(this.testPlugin.PreRequest);
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            // Initialize validation rules that apply to all requests in the WebTest
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidateResponseUrl validationRule1 = new ValidateResponseUrl();
                this.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule1.Validate);
            }
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidationRuleResponseTimeGoal validationRule2 = new ValidationRuleResponseTimeGoal();
                validationRule2.Tolerance = 0D;
                this.ValidateResponseOnPageComplete += new EventHandler<ValidationEventArgs>(validationRule2.Validate);
            }

            WebTestRequest request1 = new WebTestRequest("http://uat.niceiconline.com/");
            WebTestRequest request1Dependent1 = new WebTestRequest("http://uat.niceiconline.com/static/css/fonts/OpenSans-Light.woff");
            request1Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "http://uat.niceiconline.com/"));
            request1.DependentRequests.Add(request1Dependent1);
            WebTestRequest request1Dependent2 = new WebTestRequest("http://uat.niceiconline.com/static/css/fonts/OpenSans.woff");
            request1Dependent2.Headers.Add(new WebTestRequestHeader("Referer", "http://uat.niceiconline.com/"));
            request1.DependentRequests.Add(request1Dependent2);
            WebTestRequest request1Dependent3 = new WebTestRequest("http://uat.niceiconline.com/static/css/fonts/OpenSans-SemiBold.woff");
            request1Dependent3.Headers.Add(new WebTestRequestHeader("Referer", "http://uat.niceiconline.com/"));
            request1.DependentRequests.Add(request1Dependent3);
            WebTestRequest request1Dependent4 = new WebTestRequest("http://uat.niceiconline.com/static/css/fonts/OpenSans-Bold.woff");
            request1Dependent4.Headers.Add(new WebTestRequestHeader("Referer", "http://uat.niceiconline.com/"));
            request1.DependentRequests.Add(request1Dependent4);
            WebTestRequest request1Dependent5 = new WebTestRequest("http://uat.niceiconline.com/static/css/fonts/OpenSans-ExtraBold.woff");
            request1Dependent5.ThinkTime = 1;
            request1Dependent5.Headers.Add(new WebTestRequestHeader("Referer", "http://uat.niceiconline.com/"));
            request1.DependentRequests.Add(request1Dependent5);
            yield return request1;
            request1 = null;
            
            WebTestRequest request2 = new WebTestRequest("http://uat.niceiconline.com/login");
            request2.Headers.Add(new WebTestRequestHeader("Referer", "http://uat.niceiconline.com/"));
            ExtractHiddenFields extractionRule1 = new ExtractHiddenFields();
            extractionRule1.Required = true;
            extractionRule1.HtmlDecode = true;
            extractionRule1.ContextParameterName = "1";
            request2.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule1.Extract);
            yield return request2;
            request2 = null;

            WebTestRequest request3 = new WebTestRequest("http://uat.niceiconline.com/login_check");
            request3.ExpectedResponseUrl = "http://uat.niceiconline.com/";
            FormPostHttpBody request3Body = new FormPostHttpBody();
            request3Body.FormPostParameters.Add("_username", "paulcollins1");
            request3Body.FormPostParameters.Add("_password", "warwick");
            //request3Body.FormPostParameters.Add("_target_path", this.Context["$HIDDEN1._target_path"].ToString());
            request3.Body = request3Body;
            request3.Method = "POST";

            WebTestRequest request3Dependent1 = new WebTestRequest("http://uat.niceiconline.com/widgets/quickLinks");
            request3Dependent1.Headers.Add(new WebTestRequestHeader("Accept", "text/html, */*; q=0.01"));
            request3Dependent1.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request3Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "http://uat.niceiconline.com/dashboard"));
            request3.DependentRequests.Add(request3Dependent1);
            WebTestRequest request3Dependent2 = new WebTestRequest("http://uat.niceiconline.com/widgets/niceicNews");
            request3Dependent2.Headers.Add(new WebTestRequestHeader("Accept", "text/html, */*; q=0.01"));
            request3Dependent2.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request3Dependent2.Headers.Add(new WebTestRequestHeader("Referer", "http://uat.niceiconline.com/dashboard"));
            request3.DependentRequests.Add(request3Dependent2);
            WebTestRequest request3Dependent3 = new WebTestRequest("http://uat.niceiconline.com/widgets/recentNotifications");
            request3Dependent3.Headers.Add(new WebTestRequestHeader("Accept", "text/html, */*; q=0.01"));
            request3Dependent3.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request3Dependent3.Headers.Add(new WebTestRequestHeader("Referer", "http://uat.niceiconline.com/dashboard"));
            request3.DependentRequests.Add(request3Dependent3);
            WebTestRequest request3Dependent4 = new WebTestRequest("http://uat.niceiconline.com/widgets/niceicOffers");
            request3Dependent4.Headers.Add(new WebTestRequestHeader("Accept", "text/html, */*; q=0.01"));
            request3Dependent4.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request3Dependent4.Headers.Add(new WebTestRequestHeader("Referer", "http://uat.niceiconline.com/dashboard"));
            request3.DependentRequests.Add(request3Dependent4);
            WebTestRequest request3Dependent5 = new WebTestRequest("http://uat.niceiconline.com/widgets/accountBalance");
            request3Dependent5.Headers.Add(new WebTestRequestHeader("Accept", "text/html, */*; q=0.01"));
            request3Dependent5.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request3Dependent5.Headers.Add(new WebTestRequestHeader("Referer", "http://uat.niceiconline.com/dashboard"));
            request3.DependentRequests.Add(request3Dependent5);
            WebTestRequest request3Dependent6 = new WebTestRequest("http://uat.niceiconline.com/widgets/recentActivity");
            request3Dependent6.Headers.Add(new WebTestRequestHeader("Accept", "text/html, */*; q=0.01"));
            request3Dependent6.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request3Dependent6.Headers.Add(new WebTestRequestHeader("Referer", "http://uat.niceiconline.com/dashboard"));
            request3.DependentRequests.Add(request3Dependent6);
            WebTestRequest request3Dependent7 = new WebTestRequest("http://uat.niceiconline.com/css/generated/fonts/nocs.eot");
            request3Dependent7.Headers.Add(new WebTestRequestHeader("Referer", "http://uat.niceiconline.com/dashboard"));
            request3Dependent7.QueryStringParameters.Add("", "6339153", false, false);
            request3.DependentRequests.Add(request3Dependent7);
            yield return request3;
            request3 = null;

            WebTestRequest request4 = new WebTestRequest("http://uat.niceiconline.com/login_check");
            request4.Method = "POST";
            request4.ExpectedResponseUrl = "http://uat.niceiconline.com/dashboard";
            request4.Headers.Add(new WebTestRequestHeader("Referer", "http://uat.niceiconline.com/login"));
            FormPostHttpBody request4Body = new FormPostHttpBody();
            request4Body.FormPostParameters.Add("_username", "paulcollins1");
            request4Body.FormPostParameters.Add("_password", "warwick");
            request4Body.FormPostParameters.Add("_target_path", this.Context["$HIDDEN1._target_path"].ToString());
            request4.Body = request4Body;
            yield return request4;
            request4 = null;

            WebTestRequest request5 = new WebTestRequest("http://uat.niceiconline.com/notification/report");
            request5.Headers.Add(new WebTestRequestHeader("Referer", "http://uat.niceiconline.com/dashboard"));
            WebTestRequest request5Dependent1 = new WebTestRequest("http://uat.niceiconline.com/css/generated/fonts/nocs.eot");
            request5Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "http://uat.niceiconline.com/notification/report"));
            request5Dependent1.QueryStringParameters.Add("", "6339153", false, false);
            request5.DependentRequests.Add(request5Dependent1);
            yield return request5;
            request5 = null;

            WebTestRequest request6 = new WebTestRequest("http://uat.niceiconline.com/notification/create");
            request6.ParseDependentRequests = false;
            request6.Headers.Add(new WebTestRequestHeader("Referer", "http://uat.niceiconline.com/notification/report"));
            WebTestRequest request6Dependent1 = new WebTestRequest("http://uat.niceiconline.com/css/generated/fonts/nocs.eot");
            request6Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "http://uat.niceiconline.com/notification/create"));
            request6Dependent1.QueryStringParameters.Add("", "6339153", false, false);
            request6.DependentRequests.Add(request6Dependent1);
            ExtractHiddenFields extractionRule2 = new ExtractHiddenFields();
            extractionRule2.Required = true;
            extractionRule2.HtmlDecode = true;
            extractionRule2.ContextParameterName = "1";
            request6.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule2.Extract);
            yield return request6;
            request6 = null;

            WebTestRequest request7 = new WebTestRequest("http://uat.niceiconline.com/account/postcodeLookup");
            //plugin
            WebTestDependentFilteryyy myFilterPlugin = new WebTestDependentFilteryyy();
            request7.PreRequest += new EventHandler<PreRequestEventArgs>(myFilterPlugin.PreRequest);

            request7.ThinkTime = 39;
            request7.Method = "POST";
            request7.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request7.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request7.Headers.Add(new WebTestRequestHeader("Referer", "http://uat.niceiconline.com/notification/create"));
            FormPostHttpBody request7Body = new FormPostHttpBody();
            request7Body.FormPostParameters.Add("postcode", "LU5 5ZX");
            request7.Body = request7Body;
            yield return request7;
            request7 = null;

            WebTestRequest request8 = new WebTestRequest("http://uat.niceiconline.com/notification/create");

            //create an instance of a plugin
            request8.ParseDependentRequests = false;

            request8.Method= "POST";
            request8.ExpectedResponseUrl = "http://uat.niceiconline.com/notification/details";
            FormPostHttpBody request8Body = new FormPostHttpBody();
            request8Body.FormPostParameters.Add("postcode", "LU5 5ZX");
            request8Body.FormPostParameters.Add("premise_list", "dp_01888882_1A");
            request8Body.FormPostParameters.Add("premise", "Warwick House");
            request8Body.FormPostParameters.Add("address1", "Houghton Hall Park");
            request8Body.FormPostParameters.Add("address2", "");
            request8Body.FormPostParameters.Add("town", "Dunstable");
            request8Body.FormPostParameters.Add("locality", this.Context["$HIDDEN1.locality"].ToString());
            request8Body.FormPostParameters.Add("county", this.Context["$HIDDEN1.county"].ToString());
            request8Body.FormPostParameters.Add("authority", "00KC");
            request8Body.FormPostParameters.Add("po_number", "");
            request8Body.FormPostParameters.Add("location", "117");
            request8.Body = request8Body;
            WebTestRequest request8Dependent1 = new WebTestRequest("http://uat.niceiconline.com/css/generated/fonts/nocs.eot");
            request8Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "http://uat.niceiconline.com/notification/details"));
            request8Dependent1.QueryStringParameters.Add("", "6339153", false, false);
            request8.DependentRequests.Add(request8Dependent1);
            ExtractHiddenFields extractionRule3 = new ExtractHiddenFields();
            extractionRule3.Required = true;
            extractionRule3.HtmlDecode = true;
            extractionRule3.ContextParameterName = "2";
            request8.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule3.Extract);
            yield return request8;
            request8 = null;

            WebTestRequest request9 = new WebTestRequest("http://uat.niceiconline.com/notification/create");
            request9.Method = "POST";
            request9.ParseDependentRequests = false;

            request9.ExpectedResponseUrl = "http://uat.niceiconline.com/notification/details";
            request9.Headers.Add(new WebTestRequestHeader("Referer", "http://uat.niceiconline.com/notification/create"));
            FormPostHttpBody request9Body = new FormPostHttpBody();
            request9Body.FormPostParameters.Add("postcode", "LU5 5ZX");
            request9Body.FormPostParameters.Add("premise_list", "dp_01888882_1A");
            request9Body.FormPostParameters.Add("premise", "Warwick House");
            request9Body.FormPostParameters.Add("address1", "Houghton Hall Park");
            request9Body.FormPostParameters.Add("address2", "");
            request9Body.FormPostParameters.Add("town", "Dunstable");
            request9Body.FormPostParameters.Add("locality", this.Context["$HIDDEN1.locality"].ToString());
            request9Body.FormPostParameters.Add("county", this.Context["$HIDDEN1.county"].ToString());
            request9Body.FormPostParameters.Add("authority", "00KC");
            request9Body.FormPostParameters.Add("po_number", "");
            request9Body.FormPostParameters.Add("location", "117");
            request9.Body = request9Body;
            yield return request9;
            request9 = null;

            WebTestRequest request10 = new WebTestRequest("http://uat.niceiconline.com/notification/getDescriptors");
            request10.ThinkTime = 102;
            request10.Headers.Add(new WebTestRequestHeader("Accept", "*/*"));
            request10.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request10.Headers.Add(new WebTestRequestHeader("Referer", "http://uat.niceiconline.com/notification/details"));
            request10.QueryStringParameters.Add("scheme", "55", false, false);
            request10.QueryStringParameters.Add("_", "1559678207548", false, false);
            yield return request10;
            request10 = null;

            WebTestRequest request11 = new WebTestRequest("http://uat.niceiconline.com/notification/details");
            request11.Method = "POST";
            request11.ExpectedResponseUrl = "http://uat.niceiconline.com/notification/confirm";
            FormPostHttpBody request11Body = new FormPostHttpBody();
           // request11Body.FormPostParameters.Add("full_descriptor_list", this.Context["$HIDDEN2.full_descriptor_list"].ToString()); //
            request11Body.FormPostParameters.Add("date_of_work", "01/06/2019");
            request11Body.FormPostParameters.Add("scheme", "55");
            request11Body.FormPostParameters.Add("descriptors[]", "457");
            request11Body.FormPostParameters.Add("descriptors[]", "458");
            request11Body.FormPostParameters.Add("descriptors[]", "459");
            request11Body.FormPostParameters.Add("descriptors[]", "460");
            request11Body.FormPostParameters.Add("descriptors[]", "461");
            request11Body.FormPostParameters.Add("descriptors[]", "462");
            request11Body.FormPostParameters.Add("greendeal", "1");
            request11Body.FormPostParameters.Add("registration_number", "999999000");
            request11Body.FormPostParameters.Add("cert_number", "24897548");
            //request11Body.FormPostParameters.Add("form_selected[]", this.Context["$HIDDEN2.form_selected[]"].ToString());
            //request11Body.FormPostParameters.Add("form_selected[]", this.Context["$HIDDEN2.form_selected[]"].ToString());
            //request11Body.FormPostParameters.Add("form_selected[]", this.Context["$HIDDEN2.form_selected[]"].ToString());
            //request11Body.FormPostParameters.Add("form_selected[]", this.Context["$HIDDEN2.form_selected[]"].ToString());
            //request11Body.FormPostParameters.Add("form_selected[]", this.Context["$HIDDEN2.form_selected[]"].ToString());
            //request11Body.FormPostParameters.Add("form_selected[]", this.Context["$HIDDEN2.form_selected[]"].ToString());
            request11.Body = request11Body;
            WebTestRequest request11Dependent1 = new WebTestRequest("http://uat.niceiconline.com/css/generated/fonts/nocs.eot");
            request11Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "http://uat.niceiconline.com/notification/confirm"));
            request11Dependent1.QueryStringParameters.Add("", "6339153", false, false);
            request11.DependentRequests.Add(request11Dependent1);
            yield return request11;
            request11 = null;

            WebTestRequest request12 = new WebTestRequest("http://uat.niceiconline.com/notification/details");
            request12.Method = "POST";
            request12.ExpectedResponseUrl = "http://uat.niceiconline.com/notification/confirm";
            request12.Headers.Add(new WebTestRequestHeader("Referer", "http://uat.niceiconline.com/notification/details"));
            FormPostHttpBody request12Body = new FormPostHttpBody();
            //request12Body.FormPostParameters.Add("full_descriptor_list", this.Context["$HIDDEN2.full_descriptor_list"].ToString());
            request12Body.FormPostParameters.Add("date_of_work", "01/06/2019");
            request12Body.FormPostParameters.Add("scheme", "55");
            request12Body.FormPostParameters.Add("descriptors[]", "457");
            request12Body.FormPostParameters.Add("descriptors[]", "458");
            request12Body.FormPostParameters.Add("descriptors[]", "459");
            request12Body.FormPostParameters.Add("descriptors[]", "460");
            request12Body.FormPostParameters.Add("descriptors[]", "461");
            request12Body.FormPostParameters.Add("descriptors[]", "462");
            request12Body.FormPostParameters.Add("greendeal", "1");
            request12Body.FormPostParameters.Add("registration_number", "999999000");
            request12Body.FormPostParameters.Add("cert_number", "24897548");
            //request12Body.FormPostParameters.Add("form_selected[]", this.Context["$HIDDEN2.form_selected[]"].ToString());
            //request12Body.FormPostParameters.Add("form_selected[]", this.Context["$HIDDEN2.form_selected[]"].ToString());
            //request12Body.FormPostParameters.Add("form_selected[]", this.Context["$HIDDEN2.form_selected[]"].ToString());
            //request12Body.FormPostParameters.Add("form_selected[]", this.Context["$HIDDEN2.form_selected[]"].ToString());
            //request12Body.FormPostParameters.Add("form_selected[]", this.Context["$HIDDEN2.form_selected[]"].ToString());
            //request12Body.FormPostParameters.Add("form_selected[]", this.Context["$HIDDEN2.form_selected[]"].ToString());
            request12.Body = request12Body;
            yield return request12;
            request12 = null;

            WebTestRequest request13 = new WebTestRequest("http://uat.niceiconline.com/notification/confirm");
            request13.Method = "POST";
            request13.ExpectedResponseUrl = "http://uat.niceiconline.com/notification/success";
            FormPostHttpBody request13Body = new FormPostHttpBody();
            request13Body.FormPostParameters.Add("enotification", "on");
            request13Body.FormPostParameters.Add("original_postcode", "");
            request13Body.FormPostParameters.Add("original_addressee", "");
            request13Body.FormPostParameters.Add("original_premise", "");
            request13Body.FormPostParameters.Add("original_address1", "");
            request13Body.FormPostParameters.Add("original_address2", "");
            request13Body.FormPostParameters.Add("original_town", "");
            request13Body.FormPostParameters.Add("enotification_send_email", "on");
            request13Body.FormPostParameters.Add("enotification_send_email_address", "divine.agbor@certsure.com");
            request13Body.FormPostParameters.Add("enotification_send_email_message", "Please find attached a digital eNotification copy of your Building Control Compli" +
                    "ance certificate.");
            request13Body.FormPostParameters.Add("postcode", "");
            request13Body.FormPostParameters.Add("addressee", "");
            request13Body.FormPostParameters.Add("premise", "");
            request13Body.FormPostParameters.Add("address1", "");
            request13Body.FormPostParameters.Add("address2", "");
            request13Body.FormPostParameters.Add("town", "");
            request13.Body = request13Body;
            WebTestRequest request13Dependent1 = new WebTestRequest("http://uat.niceiconline.com/css/generated/fonts/nocs.eot");
            request13Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "http://uat.niceiconline.com/notification/success"));
            request13Dependent1.QueryStringParameters.Add("", "6339153", false, false);
            request13.DependentRequests.Add(request13Dependent1);
            yield return request13;
            request13 = null;

            WebTestRequest request14 = new WebTestRequest("http://uat.niceiconline.com/notification/confirm");
            request14.ParseDependentRequests = false;
            request14.Method = "POST";
            request14.ExpectedResponseUrl = "http://uat.niceiconline.com/notification/index";
            request14.Headers.Add(new WebTestRequestHeader("Referer", "http://uat.niceiconline.com/notification/confirm"));
            FormPostHttpBody request14Body = new FormPostHttpBody();
            request14Body.FormPostParameters.Add("enotification", "on");
            request14Body.FormPostParameters.Add("original_postcode", "");
            request14Body.FormPostParameters.Add("original_addressee", "");
            request14Body.FormPostParameters.Add("original_premise", "");
            request14Body.FormPostParameters.Add("original_address1", "");
            request14Body.FormPostParameters.Add("original_address2", "");
            request14Body.FormPostParameters.Add("original_town", "");
            request14Body.FormPostParameters.Add("enotification_send_email", "on");
            request14Body.FormPostParameters.Add("enotification_send_email_address", "divine.agbor@certsure.com");
            request14Body.FormPostParameters.Add("enotification_send_email_message", "Please find attached a digital eNotification copy of your Building Control Compli" +
                    "ance certificate.");
            request14Body.FormPostParameters.Add("postcode", "");
            request14Body.FormPostParameters.Add("addressee", "");
            request14Body.FormPostParameters.Add("premise", "");
            request14Body.FormPostParameters.Add("address1", "");
            request14Body.FormPostParameters.Add("address2", "");
            request14Body.FormPostParameters.Add("town", "");
            request14.Body = request14Body;
            yield return request14;
            request14 = null;
        }
    }
}
